# Generated by Django 4.0.5 on 2022-06-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Student',
        ),
    ]
